### ISSUE TITLE
请问trt版本的yolo-pose是yolov5原版的预测还是带人体关键点的预测的？

### ISSUE THREAD

**Issue by PaulX1029** [BingfengYan/yolo_pose#1]
May I ask whether the yolo-pose of the trt version is the prediction of the original version of yolov5 or the prediction with the key points of the human body?
期待您的回复，谢谢！

**Comment by fengxiuyaun** [comment]
带pose的

**Comment by fengxiuyaun** [comment]
由于上传的匆忙，还没写详细的readme。大体上是先从pytorch通过gen_wts.py把模型导出来。然后使用yolo_pose里边的C代码生成.engine；然后可以使用对应的.py脚本调用engine了。

**Comment by fengxiuyaun** [comment]
欢迎star

**Comment by PaulX1029** [comment]
已经star，我想借鉴您的c版本前后处理，这样是可以跑通的吧？

**Comment by fengxiuyaun** [comment]
应该是可以的（由于yolov5版本很多，网络结构上可能要稍微修改一下）。不过大多坑我都踩过了，有什么问题可以随时交流

**Comment by PaulX1029** [comment]
好的，感谢！

**Comment by PaulX1029** [comment]
我想再问一下 onnx推理的模型可以提供一下吗？用原版的官方的转换有点不成功

**Comment by PaulX1029** [comment]
readme中给的模型下载链接都已经失效了（也可能是我这边打不开）

**Comment by fengxiuyaun** [comment]
Add WeChat ？ My number is bphegyan2
