### ISSUE TITLE
大佬，请问一下tensorrt版的yolo pose能运行吗？

### ISSUE THREAD

**Issue by jacke121** [BingfengYan/yolo_pose#2]
大佬，请教一下，我用你这个tensorrt的代码跑 Yolov5s6_pose_640生成的tensorrt模型，结果为空呢

**Comment by fengxiuyaun** [comment]
你是如何做的呢？我这边也是用的这个模型是可以的

**Comment by fengxiuyaun** [comment]
可以说一下你的步骤，我看看有啥问题

**Comment by jacke121** [comment]
你这个是4个关键点把？













--

never give up




在 2022-11-01 13:07:54，"BingfengYan" ***@***.***> 写道：

你是如何做的呢？我这边也是用的这个模型是可以的

**Comment by fengxiuyaun** [comment]
yeah
